Feature/marc puigdemont/add unit tests to circleci
lesfieres/vue-viewer pull request #7
Opened 2019-03-29 14:42 UTC by MarcPuigdemont

I have refactored, reordered and added unit tests job/workflow to circleci file.

Now we get two jobs on circleci, one for unit tests and one for e2e:

![Screenshot 2019-03-29 at 15 39 56](https://user-images.githubusercontent.com/15010937/55240422-27736c00-5239-11e9-9e1e-1e93b5686a96.png)

If you look at the third column, you'll see these two jobs are different, but triggered for the same commit

2019-03-29 17:33 UTC, mverdaguer commented on .circleci/npm-install-orient-express.sh
> +if [ -f "install-orient-express" ]
I love this trick.

2019-03-29 17:35 UTC, mverdaguer requested changes

2019-03-29 17:35 UTC, mverdaguer commented on tests/e2e/specs/books-navigation.js
> +      .getLog('browser', logEntriesArray => console.log(logEntriesArray))
Oh, now that you are at it remove these logs, I forgot to remove them in my PR xD

2019-03-29 19:31 UTC, mverdaguer approved these changes

2019-04-01 05:48 UTC, marcmortensen approved these changes

2019-04-01 05:51 UTC, merged